version: '3'
services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"  # Maps port 8501 on your host to port 8501 in the container
    volumes:
      - .:/app       # Maps the current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run your_script.py --server.port 8501

