version: '3'
services:
  nippo_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile	
    ports:
      - "8501:8501"  # Maps port 8501 on your host to port 8501 in the container
    volumes:
      - ../myapp:/app       # Maps the current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py --server.port 8501
    restart: always

